project_id = "zdrkjohyctkisesidodo"

[functions.recommend-movies]
verify_jwt = false

[functions.movie-details]
verify_jwt = false

[functions.search-movies]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.trending-movies]
verify_jwt = false

[functions.person-details]
verify_jwt = false